### ISSUE TITLE
 bug with yaml long string

### ISSUE THREAD

**Issue by zhaogaolong** [sters/yaml-diff#52]
I want diff long string values,  but give worng result

test case

c.yaml
```yaml
data:
  config: |
    logging.a: false
    logging.b: false
```
d.yaml
```yaml
data:
  config: |
    logging.a: false
    logging.c: false
```
the `c.yaml`  delete `logging.b: false` and add `logging.c: false`

but result:
```diff
--- example/c.ymal
+++ example/d.yaml

  data:
-   config: "logging.a: false
logging.b: false
"
+   config: "logging.a: false
logging.c: false

"
```

The correct result is
<img width="866" alt="图片" src="https://github.com/sters/yaml-diff/assets/13202101/860ceb5d-b9a9-4d3e-bd90-6e05d34dcfc6">
